### ISSUE TITLE
Glyphs for OpenSans fonts not building

### ISSUE THREAD

**Issue by nextstopsun** [sputnik-maps/mvt-styler#2]
I'm trying to build glyphs for a basic set of OpenSans fonts.
TTF files are downloaded from [here](http://www.1001fonts.com/open-sans-font.html)
When running `./build.sh` I get 
```
./build.sh 
++ ls OpenSans-Bold.ttf OpenSans-BoldItalic.ttf OpenSans-ExtraBold.ttf OpenSans-ExtraBoldItalic.ttf OpenSans-Italic.ttf OpenSans-Light.ttf OpenSans-LightItalic.ttf OpenSans-Regular.ttf OpenSans-Semibold.ttf OpenSans-SemiboldItalic.ttf glyphicons-halflings-regular.ttf
+ for fnt in `ls *.ttf`
++ echo OpenSans-Bold.ttf
++ sed s/.ttf//
+ dir=OpenSans-Bold
+ dir=glyphs/OpenSans-Bold
+ mkdir -p glyphs/OpenSans-Bold
+ ./node_modules/.bin/build-glyphs OpenSans-Bold.ttf glyphs/OpenSans-Bold
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /opt/mvt-styler/fonts/node_modules/fontnik/lib/fontnik.node: undefined symbol: _ZNK6google8protobuf11MessageLite25InitializationErrorStringB5cxx11Ev
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/mvt-styler/fonts/node_modules/fontnik/index.js:1:80)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by orofarne** [comment]
Hi! I think, libprotobuf is required. Documentation should be updated.
